# Generated by Django 5.0.2 on 2024-02-27 13:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='')),
                ('certifications', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('urgent_examination', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('governorate', models.CharField(max_length=50)),
                ('offer_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('offer_end_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
