# Generated by Django 5.0.2 on 2024-02-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_remove_customer_age_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
