# Generated by Django 5.0.2 on 2024-02-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_doctor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
    ]
