# Generated by Django 5.0.2 on 2024-02-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_id',
        ),
    ]
