# Generated by Django 5.0.2 on 2024-02-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_rename_customer_appointment_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
