# Generated by Django 5.0.2 on 2024-03-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
