# Generated by Django 5.0.2 on 2024-03-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_delete_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.customer')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.doctor')),
            ],
        ),
    ]
