# Generated by Django 5.0.2 on 2024-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='question1',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor')], default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question2',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor')], default='Good', max_length=10),
        ),
    ]
