# Generated by Django 5.0.2 on 2024-03-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
