# Generated by Django 5.0.2 on 2024-03-11 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
