# Generated by Django 5.0.2 on 2024-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_doctor_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1, null=True),
        ),
    ]
