# Generated by Django 5.0.2 on 2024-03-13 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0027_alter_doctor_rating_alter_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTeamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.customer')),
            ],
        ),
    ]
