# Generated by Django 5.0.2 on 2024-03-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0028_supportteammessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportteammessage',
            old_name='created_at',
            new_name='date',
        ),
    ]
