# Generated by Django 5.0.2 on 2024-03-14 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0029_rename_created_at_supportteammessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='offline_customer_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='offline_customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01*******'", regex='^01[0-9]{9}$')]),
        ),
    ]
