# Generated by Django 5.0.2 on 2024-03-14 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0031_alter_appointment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='offline_customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01*******'", regex='^01[0-9]{9}$')]),
        ),
    ]
