# Generated by Django 5.0.2 on 2024-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0032_alter_appointment_offline_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True),
        ),
    ]
