# Generated by Django 5.0.2 on 2024-03-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0035_alter_doctor_offer_percentage_alter_doctor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
