# Generated by Django 5.0.2 on 2024-03-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0036_alter_doctor_offer_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
