# Generated by Django 5.0.2 on 2024-03-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0038_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
