# Generated by Django 5.0.2 on 2024-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0039_alter_doctor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
