# Generated by Django 5.0.2 on 2024-03-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0040_customer_email_verified_doctor_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='customer',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_chats', to='Application.chat'),
        ),
    ]
