# Generated by Django 5.0.2 on 2024-04-07 21:23

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0041_remove_customer_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(upload_to=Application.models.PathAndRename('Images')),
        ),
    ]
