# Generated by Django 5.0.2 on 2024-04-08 17:56

import Application.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0046_alter_doctor_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(upload_to=Application.models.PathAndRename('Profile_Photos')),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CREATED', 'Appointment created'), ('CANCELED', 'Appointment canceled'), ('APPOINTMENT_DONE', 'Appointment done'), ('DOCTOR_CANCELED', 'Doctor canceled appointment'), ('REMINDER', 'Appointment reminder'), ('NEWS', 'News added')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Application.customer')),
            ],
            options={
                'ordering': ['-created_date', '-created_time'],
            },
        ),
    ]
