# Generated by Django 5.0.2 on 2024-04-09 17:13

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0047_alter_doctor_profile_photo_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certifications',
            field=models.ImageField(upload_to=Application.models.PathAndRename('Certifications')),
        ),
    ]
