# Generated by Django 5.0.2 on 2024-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0049_customer_appointments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointments_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
