# Generated by Django 5.0.2 on 2024-04-10 12:44

import Application.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0050_doctor_appointments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certifications',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 300], upload_to=Application.models.PathAndRename('Certifications')),
        ),
    ]
