# Generated by Django 5.0.2 on 2024-04-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0057_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportteammessage',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
