# Generated by Django 5.0.2 on 2024-04-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0060_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('type', models.CharField(choices=[('Cat', 'Cat'), ('Dof', 'Dog'), ('Turtle', 'Turtle'), ('Monkey', 'Monkey'), ('Other', 'Other')], default='Other', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PetPreviousReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('dose1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dose2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dose3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.pet')),
            ],
        ),
    ]
