# Generated by Django 5.0.2 on 2024-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0061_pet_petpreviousreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Turtle', 'Turtle'), ('Monkey', 'Monkey'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
