# Generated by Django 5.0.2 on 2024-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0062_alter_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpreviousreports',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
