# Generated by Django 5.0.2 on 2024-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0063_petpreviousreports_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
