# Generated by Django 5.0.2 on 2024-04-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0065_doctor_day_off_doctor_finish_time_doctor_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='day_off',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('None', 'None')], max_length=10),
        ),
    ]
