# Generated by Django 5.0.2 on 2024-04-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0066_alter_doctor_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.CharField(default='12:00 am', max_length=10),
        ),
    ]
