# Generated by Django 5.0.2 on 2024-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0068_remove_doctor_appointment_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
