# Generated by Django 5.0.2 on 2024-04-22 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0069_alter_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_msg',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_msg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
