# Generated by Django 5.0.2 on 2024-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0070_chat_last_msg_chat_last_msg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_msg_seen',
            field=models.BooleanField(default=False),
        ),
    ]
