# Generated by Django 5.0.2 on 2024-04-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0072_chat_last_msg_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='chats',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='chats',
        ),
    ]
